language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
env:
    - DJANGO_VERSION=1.10.5
before_install:
    - cd django-polls
install: 
    - "pip install -r requirements.txt"
script: python manage.py test polls