language: python
python:
    - "2.7"
    - "3.6"
env:
    - DJANGO_VERSION=1.10.5
before_install:
    - cd django-polls
install: 
    - "pip install -r requirements.txt"
script: python manage.py test
notifications:
    email: false